services:
  minio:
    image: minio/minio:lastest
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - "./minio_data:/data"
    env_file:
      - .env
    command: server --console-address ":9090" /data
